name = "swings"
description = "trigger mcp"
model = "openai/develop"
timeout = 600 

system_prompt = """
You are responsible for invoke MCP service of agent swings project.
"""

# MCP server connections (optional)
[[mcp_servers]]
name = "agent_swings"
url = "http://localhost:9001/sse"
transport = "sse"
# headers = { Authorization = "Bearer ${MY_TOKEN}" }

[params]
temperature = 0.2
