services:
  kroki:
    image: yuzutech/kroki
    ports:
      - "8000:8000"
    environment:
      - KROKI_MERMAID_HOST=mermaid
    depends_on:
      - mermaid

  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"
